name: Build and Deploy Production Environment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Set Yarn nodeLinker
        run: yarn config set nodeLinker node-modules
      - name: Install Dependencies
        run: yarn install
      - name: Get Vercel Environment Variables
        run: yarn vercel pull --environment=production --token=${{ secrets.VERCEL_TOKEN }} --yes
      - name: Build and Deploy
        run: yarn vercel-build:prod
